var { verifyToken } = require("../helpers/auth");
const multer = require("multer");
const upload = multer({ dest: "uploads/" });
var path = require("path");

module.exports = function (app, ensureAuth) {
  var index = require("../endpoints/index");
  var web_auth = require("../endpoints/web_auth");
  var protectedR = require("../endpoints/protected"); //test route for protected endpoint;
  var registration = require("../endpoints/registration");
  var confirm_user_by_email = require("../endpoints/confirm_user_by_email");
  var reset_password = require("../endpoints/reset_password");
  var do_reset = require("../endpoints/do_reset");
  var find_nearest_stops = require("../endpoints/find_nearest_stops");
  var recalculate_stops = require("../endpoints/recalculate_stops");
  var saveRoute = require("../endpoints/save_route");
  var getRoutes = require("../endpoints/get_routes");
  var deleteRoute = require("../endpoints/delete_route");
  var getSingleRoutes = require("../endpoints/get_single_route");
  var download_gtfx = require("../endpoints/download_gtfx");
  var get_services = require("../endpoints/get_services");
  var get_service = require("../endpoints/get_service");
  var update_service = require("../endpoints/update_service");
  var delete_service = require("../endpoints/delete_service");
  var get_agencies = require("../endpoints/get_agencies");
  var get_agency = require("../endpoints/get_agency");
  var getRoute = require("../endpoints/get_route");
  var new_agency = require("../endpoints/new_agency");
  var delete_agency = require("../endpoints/delete_agency");
  var get_gtfs = require("../endpoints/get_gtfs");
  var view_visualization = require("../endpoints/view_visualization");
  var display_timetable = require("../endpoints/display_timetable");
  var download_gtfs = require("../endpoints/download_gtfs_file");
  var get_stops = require("../endpoints/get_stops");
  var get_stop = require("../endpoints/get_stop");
  var new_stop = require("../endpoints/new_stop");
  var dashboard_count = require("../endpoints/dashboard_count");
  var average_speed = require("../endpoints/average_speed");
  var get_osrm = require("../endpoints/osrm");
  var delete_stop = require("../endpoints/delete_stop");
  var get_user = require("../endpoints/get_user");
  var add_multiple_stops = require("../endpoints/add_multiple_stops");
  var add_multiple_agency = require("../endpoints/add_multiple_agency");
  var add_multiple_calender = require("../endpoints/add_multiple_calender");
  var convert_json = require("../endpoints/convert_togeojson");
  //PUBLIC ENDPOINTS
  app.use("/", index);
  app.use("/getUser", get_user);
  app.use("/recalculate_stops", recalculate_stops); //temporal to create geoSpatial index
  app.use("/auth/web", web_auth);
  app.use("/confirm_user_by_email", confirm_user_by_email);
  app.use("/download_gtfx", download_gtfx);
  app.use("/registration", registration);
  app.use("/reset_password", reset_password);
  app.use("/do_reset", do_reset);
  app.use("/view_visualization", view_visualization);
  app.use("/display_timetable", display_timetable);
  app.use("/download_gtfs", download_gtfs);
  app.use("/dashboard_count", dashboard_count);
  app.use("/average_speed", average_speed);

  //PROTECTED ENDPOINTS
  app.use("/protected", verifyToken, protectedR);
  app.use("/save_route", verifyToken, saveRoute);
  app.use("/get_routes", verifyToken, getRoutes);
  app.use("/get_route", ensureAuth, getRoute);
  app.use("/get_single_route", verifyToken, getSingleRoutes);
  app.use("/delete_route", verifyToken, deleteRoute);
  app.use("/find_nearest_stops", verifyToken, find_nearest_stops);
  app.use("/get_services", verifyToken, get_services);
  app.use("/get_service", verifyToken, get_service);
  app.use("/add_multiple_calender", verifyToken, add_multiple_calender);
  app.use("/update_service", verifyToken, update_service);
  app.use("/delete_service", verifyToken, delete_service);
  app.use("/get_agencies", verifyToken, get_agencies);
  app.use("/add_multiple_agency", verifyToken, add_multiple_agency);
  app.use("/get_agency", ensureAuth, get_agency);
  app.use("/new_agency", verifyToken, new_agency);
  app.use("/delete_agency", verifyToken, delete_agency);
  app.use("/get_gtfs", verifyToken, get_gtfs);
  app.use("/get_stops", verifyToken, get_stops);
  app.use("/get_stop", ensureAuth, get_stop);
  app.use("/new_stop", verifyToken, new_stop);
  app.use("/add_multiple_stops", verifyToken, add_multiple_stops);
  app.use("/get_osrm", verifyToken, get_osrm);
  app.use("/delete_stop", verifyToken, delete_stop);
  app.use("/convert_json", upload.single("xml"), verifyToken, convert_json);

  // app.use("/download_gtfs", verifyToken, download_gtfs);
};
